- README.md
I have just replace the Broken url for Quick Start Guide to Start template Doc url on the README file
> Fix Quick Start Guide URL with start template doc

- core/src/constants/configSchema.tsx
name is only required to configure an external media library, but the media_library config can be used without a name to configure the max file size for example.
See in `core/src/mediaLibrary.ts` the `isExternalMediaLibraryConfig` function.
> feat: remove required name in media_library config

- packages/core/dev-test/backends/proxy/config.yml
- packages/core/dev-test/index.js
- packages/core/src/actions/media.ts
- packages/core/src/backends/proxy/implementation.ts
- packages/core/src/components/Collection/Entries/EntryCard.tsx
- packages/core/src/components/MediaLibrary/MediaLibraryCard.tsx
- packages/core/src/index.ts
- packages/core/src/interface.ts
- packages/core/src/lib/formatters.ts
- packages/core/src/lib/hooks/useMediaAsset.ts
- packages/core/src/lib/util/media.util.ts
- packages/core/src/types/global.d.ts
- fix: media not displaying with local backend
- chore: deprecate `getAsset`
Fixes #319
> fix: media not displaying with local backend

- packages/core/src/backends/gitlab/API.ts
- packages/docs/content/docs/gitlab-backend.mdx
Added the `?lfs=true` flag to GitLab file requests
This means, that if a file is stored in LFS, return the content See https://github.com/netlify/netlify-cms/issues/3704 for the upstream issue.
Any non-LFS Repos are not affected by this change. Here are the [GitLab Docs on this feature](https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository) to partially proof this.
I know that this is a bugfix, which is not on your roadmap (nor does it have an issue), but I think this should be an uncontroversial bugfix of the original project 😉
- Previous Behaviour (with LFS **enabled**):
- Current Behaviour (with LFS **disabled**):  
- Current Behaviour (with LFS **enabled**):
> feat: GitLab LFS Support

- packages/docs/content/docs/widget-list.mdx
I think the lists option could better differentiate between `field` and `fields` 
This PR tries to make the removal of `field` more apparent.
Related #356
> docs: Improve List documentation for `field` vs `fields`

- packages/docs/content/docs/add-to-your-site-bundling.mdx
This is my attempt at clarifying the bundling docs. I tried to look at the code, but I didnt understand that much. My understanding of how things work (specifically with regards to loading the config), is mostly from trial and error. This means I might have just written a bunch of garbage, but I tried.
Although since I got bundling to work with Astro, I can say for sure that the provided example is valid.
> docs: Update bundling documentation with an example using Astro

- packages/docs/content/docs/netlify-cms-migration-guide.mdx
Previously, the change for `sortable_fields` was not documented.
I have not checked, if we allow the `sortable_fields: [field1, field2]` as a shorthand, but I think even if this is the case, we should add this to the migration guide.
> docs: added `sortable_fields` to the migration guide

- packages/docs/content/docs/add-to-your-site-bundling.mdx
First of all the tense was wrong - "will be built" and "being run" in the same sentence. Not sure if "that" is superfluous or not, I'm not an English professor. In any case, it at least isn't wrong.
Also, I'm not actually sure `CMS.init()` needs to run on the client, perhaps it can be run on the server when using SSR? If so I can add something like "...on the client or during server side rendering (if applicable)".
> fix: correct tense + more explicit wording

- packages/docs/content/docs/custom-icons.mdx
This is a suggestion.
In my project, I wasn't able to use JSX syntax where I had this code. I'm thinking this might be the case for a lot of other people as well.
Even if not, the other customizing examples (adding custom previews, adding custom links & pages etc.) do not use JSX syntax, but instead, the provided React.createElement "h" alias.
> docs: use provided "h" function instead of jsx

- packages/core/src/lib/registry.ts
- packages/docs/content/docs/additional-links.mdx
- packages/docs/content/docs/custom-icons.mdx
- packages/docs/content/docs/custom-previews.mdx
- packages/docs/content/docs/custom-widgets.mdx
- packages/docs/content/docs/widget-markdown.mdx
- packages/docs/src/components/docs/components/CodeTabs.tsx
All examples showing javascript code have been updated to include `javascript`, `jsx` and `typescript`.
> docs: update examples

- packages/core/src/backends/gitea/API.ts
The commits endpoint of gitea API returns commit diff stats by default, which slows down the requests and has massive impact on overall CMS performance. This PR disables commit stats loading according to Gitea API reference.
> fix: disable commit diff (speedup)

- packages/core/src/backends/gitea/API.ts
- packages/core/src/backends/gitea/__tests__/API.spec.ts
- packages/docs/content/docs/gitea-backend.mdx
The usage of `forEach()` with asynchronous calls caused a problem where multiple file uploads would run parallel, which causes an error with Gitea unable to create multiple commits simultaneously. 
This PR refactors some parts of the Gitea backend to achieve sequential file saving.
Additional changes:
- fixed unit tests
- updated OAuth provider in docs
- added a warning about the unique behavior of the Gitea backend
> fix: gitea/refactor file saving

- packages/docs/content/docs/add-to-your-site-cdn.mdx
[Astro project structure](https://docs.astro.build/en/core-concepts/project-structure/) is also using the public folder for static assets.
> docs(add-to-your-site-cdn): adds Astro in the SSG | static folder table

- packages/core/src/lib/auth/netlify-auth.ts
Currently, when using the netlify-auth plugin, which is the main one for most backends, the standard behavior is that a popup window is opened when clicking on the authentication button. This leads to some problems:
- many modern browsers tend to block popup windows or at least offer and recommend such a setting
- popup windows lack the standard browser UI, so e.g. password manager extensions often can't be used
- when a specific browser window is set to be always on top and in-focus, popup windows aren't a good solution
This pull request would, if accepted, switch to the standardized `target="_blank"` setting to open a new tab or, optionally, a new window (some browsers allow changing that behavior) instead of a popup window for authentication.
> fix(auth): swap popup for new tab

- packages/docs/content/docs/add-to-your-site-bundling.mdx
This PR fixes a couple of broken links I noticed on the Bundling page (https://www.staticcms.org/docs/add-to-your-site-bundling)
> fix(docs): dead links on Bundling page

- packages/core/src/components/Collection/Collection.tsx
- Fixes what I'm pretty sure is a typo in the memo on determining the collection URL.
I ran into the same issue with nested collections as reported in https://github.com/StaticJsCMS/static-cms/issues/63#issuecomment-1438384129
The error points at the line changed in this PR, and after this commit I am able to successfully enter nested collections via the nav tree.
> fix: Nested collections: fix collection URL variable

- packages/core/src/components/App/App.tsx
- packages/core/src/components/Collection/CollectionRoute.tsx
- packages/core/src/components/Editor/EditorRoute.tsx
Towards #63
Complements fix for #393
The nested folders feature is currently broken.
This PR addresses routing changes, to allow for entry paths including `/` being passed to several components.
> fix: Nested Folders Feature Routing

- packages/core/src/lib/hooks/useMediaFiles.ts
- packages/core/src/locales/de/index.ts
- packages/demo/src/cms.jsx
- packages/docs/content/config.json
- packages/docs/content/docs/additional-links.mdx
- packages/docs/content/docs/beta-features.mdx
- packages/docs/content/docs/configuration-options.mdx
- packages/docs/content/docs/custom-previews.mdx
- packages/docs/content/docs/custom-widgets.mdx
- packages/docs/content/docs/typescript.mdx
- packages/docs/content/docs/widget-markdown.mdx
- update German translation for media library folders
- update some old links to staticcms.org
- update documentation for Commit Message Templates and move from beta to configuration page (after prolonged usage, some testing and a look at the code I consider it as stable), will close #230 
- fix some method name on customization pages
- fix example for media in custom previews
- add example for media library usage in markdown shortcodes
> chore: miscellaneous fixes and documentation updates

- packages/core/src/components/navbar/Sidebar.tsx
Small fix for sidebar height. When having too many entries/collections in the sidebar, scrolling is being activated. When using h-full class, the last entry is often hidden without having the possibility to scroll down. When using h-main as in the collection page, everything works as expected.
> fix: sidebar height

- tailwind.base.config.js
The stylesheet `packages/core/src/styles/inter.css` is imported but Inter font family is not configured anywhere.
It's not a bug, but since `inter.css` exists I figured the intention is to use it.
> feat: extend tailwind config to use Inter sans

- packages/core/src/lib/hooks/useMediaFiles.ts
When using media library folders in a draft entry and creating a new folder, the media library tries to fetch it's content from backend, and when it fails it falls back to the content of the previous folder. To prevent that from happening every time, this PR includes a check if the folder is a draft and simply uses a blank file list in that case.
Also some small cleanups in the code for useMediaFiles hook.
> fix: draft folders

- packages/docs/content/docs/decap-migration-guide.mdx
In the section "Static CMS Styles":
Incorrect: Static CMS bundles it styles separately... Corrected: Static CMS bundles its styles separately...
In the section "Backends":
Incorrect: The Azure backend has been remove...
Corrected: The Azure backend has been removed...
> docs: Fix typos in the Decap CMS Migration Guide

- packages/core/src/components/common/image/Image.tsx
> fix: media library placeholder image width (Firefox / Safari)

- packages/core/src/backend.ts
- packages/core/src/lib/util/__tests__/search.util.spec.ts
- packages/core/src/lib/util/search.util.ts
- packages/core/src/widgets/relation/RelationControl.tsx
> fix: properly handle search within a single entry

- packages/core/src/widgets/markdown/plate/PlateEditor.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/code/Code.css
- packages/core/src/widgets/markdown/plate/components/nodes/code/Code.tsx
> fix: inline code styles

- BREAKING_CHANGES.md
- packages/core/dev-test/config.yml
- packages/core/dev-test/index.js
- packages/core/src/components/entry-editor/editor-control-pane/EditorControlPane.tsx
- packages/core/src/interface.ts
- packages/core/src/lib/util/__tests__/field.util.spec.ts
- packages/core/src/reducers/__tests__/entryDraft.spec.ts
- packages/core/src/widgets/boolean/BooleanControl.css
- packages/core/src/widgets/boolean/BooleanControl.tsx
- packages/core/src/widgets/boolean/schema.ts
- packages/core/src/widgets/number/NumberControl.css
- packages/core/src/widgets/number/NumberControl.tsx
- packages/core/src/widgets/number/schema.ts
- packages/core/src/widgets/relation/__tests__/RelationControl.spec.ts
- packages/core/src/widgets/string/StringControl.css
- packages/core/src/widgets/string/StringControl.tsx
- packages/core/src/widgets/string/StringPreview.tsx
- packages/core/src/widgets/string/index.ts
- packages/core/src/widgets/string/schema.ts
- packages/core/src/widgets/text/TextControl.tsx
- packages/core/src/widgets/text/TextPreview.tsx
- packages/core/src/widgets/text/index.ts
- packages/core/test/data/fields.mock.ts
- packages/demo/public/config.yml
- packages/demo/src/cms.jsx
- packages/docs/content/docs/widget-boolean.mdx
- packages/docs/content/docs/widget-number.mdx
- packages/docs/content/docs/widget-string.mdx
Inspired by https://github.com/decaporg/decap-cms/pull/6836
Resolves #887
> feat: add prefix/suffix options for boolean, number and string widgets

- packages/app/webpack.config.js
- packages/core/dev-test/config.yml
- packages/core/package.json
- packages/core/src/backend.ts
- packages/core/src/lib/formatters.ts
- packages/core/src/lib/util/collection.util.ts
- packages/core/src/lib/util/field.util.ts
- packages/core/src/lib/widgets/stringTemplate.ts
- packages/core/src/widgets/datetime/DateTimeControl.tsx
- packages/core/src/widgets/datetime/datetime.util.ts
- packages/core/src/widgets/list/components/ListItem.tsx
- packages/core/src/widgets/object/ObjectControl.tsx
- packages/core/src/widgets/relation/RelationControl.tsx
- packages/core/webpack.config.js
- yarn.lock
> feat: date fns template string

- packages/core/src/components/common/autocomplete/Autocomplete.css
- packages/core/src/components/common/autocomplete/Autocomplete.tsx
- packages/core/src/components/common/progress/CircularProgress.css
- packages/core/src/styles/main.css
- packages/core/src/widgets/relation/RelationControl.css
- packages/core/src/widgets/relation/RelationControl.tsx
- tailwind.base.config.js
> fix: relation widget style fixes

- packages/core/src/components/entry-editor/editor-control-pane/EditorControl.tsx
> fix: do not use cached value for list or object

- packages/core/src/backend.ts
Related to https://github.com/decaporg/decap-cms/pull/6937
Fixes bug caused by #868
> fix: consider i18n structure when building path regex

- packages/core/src/components/entry-editor/editor-control-pane/EditorControl.tsx
- packages/core/src/widgets/string/StringControl.tsx
- packages/core/src/widgets/string/__tests__/StringControl.spec.ts
- packages/core/src/widgets/text/TextControl.tsx
- packages/core/src/widgets/text/__tests__/TextControl.spec.ts
When in the i18n side by side editor, fields marked `duplicate` or `none` are not showing updated values when the default locale's corresponding field is updated.
> fix: properly update duplicated and none i18n fields when default locale updates

- packages/core/src/backend.ts
Related to https://github.com/decaporg/decap-cms/pull/6937, https://github.com/decaporg/decap-cms/pull/6898 and #935 
Fixes bug caused by #868
Fix in decap: https://github.com/decaporg/decap-cms/pull/6942
> fix: handle single file i18n correctly

- packages/core/package.json
- packages/core/src/backend.ts
- packages/core/src/lib/formatters.ts
- packages/core/src/lib/i18n.ts
- packages/core/src/lib/util/set.util.ts
- packages/core/src/reducers/entries.ts
- packages/core/src/reducers/entryDraft.ts
- yarn.lock
> fix: replace lodash set with immutable version

- packages/core/dev-test/backends/proxy/config.yml
- packages/core/src/__tests__/testConfig.ts
- packages/core/src/components/entry-editor/EditorInterface.css
- packages/core/src/components/entry-editor/EditorInterface.tsx
- packages/core/src/components/entry-editor/editor-control-pane/EditorControlPane.tsx
- packages/core/src/components/entry-editor/editor-control-pane/LocaleDropdown.css
- packages/core/src/components/entry-editor/editor-control-pane/LocaleDropdown.tsx
- packages/core/src/lib/hooks/useMediaQuery.ts
- packages/core/src/reducers/selectors/entryDraft.ts
- packages/core/src/widgets/markdown/plate/components/buttons/common/ToolbarButton.tsx
Fixes #937 
Allow locales are now checked for errors instead of just those currently visible.
> feat: i18n better locale error handling

- packages/core/src/components/entry-editor/EditorInterface.tsx
Fix https://github.com/StaticJsCMS/static-cms/issues/955
bug: resizing the editor doesn't work correctly in Firefox due to pointer events being captured in the preview pane
> fix: resizing the editor doesn't work correctly in Firefox due to pointer events being captured in the preview pane

- packages/app/.eslintrc.js
- packages/app/babel.config.js
- packages/app/webpack.config.js
- packages/core/src/bootstrap.tsx
- packages/core/src/components/ErrorBoundary.tsx
- packages/core/src/types/constants.d.ts
- packages/docs/.eslintrc.js
- packages/tools/babel.config.js
> fix: output app version number just like core

- packages/app/.editorconfig
- packages/core/.editorconfig
- packages/core/dev-test/backends/proxy/_data/navigation.mdx
- packages/core/dev-test/backends/proxy/config.yml
- packages/core/src/formats/formats.ts
- packages/docs/.editorconfig
- packages/docs/content/docs/collection-overview.mdx
This does not provide editor support for MDX components, but simply allows the mdx file extension to be used. Static CMS will read the file just like it would a Markdown file.
Related to #81 
Resolves #963
> feat: basic support for mdx file extension

- packages/core/dev-test/config.yml
- packages/core/src/components/common/field/Hint.tsx
> fix: make hint markdown link clickable

- packages/core/src/interface.ts
- packages/core/src/lib/__tests__/registry.spec.ts
- packages/core/src/lib/hooks/useEntryCallback.ts
- packages/core/src/lib/registry.ts
- packages/docs/content/docs/cms-events.mdx
Allow event handlers for `change`, `preSave`, `postSave`, `prePublish` and `postPublish` events to be registered without a collection specified (or even a field for `change`).
Addresses #970
> feat: allow events to be registered without collection specified

- packages/core/src/__tests__/backend.spec.ts
- packages/core/src/actions/editorialWorkflow.ts
- packages/core/src/actions/entries.ts
- packages/core/src/backend.ts
- packages/core/src/formats/FileFormatter.ts
- packages/core/src/formats/YamlFormatter.ts
- packages/core/src/formats/__tests__/YamlFormatter.spec.ts
- packages/core/src/formats/frontmatter.ts
- packages/core/src/interface.ts
- packages/core/src/lib/__tests__/registry.spec.ts
- packages/docs/content/docs/configuration-options.mdx
> feat: allow yaml parse/stringify options in config

- packages/core/dev-test/config.yml
- packages/core/src/components/navbar/Navbar.tsx
- packages/core/src/constants/configSchema.tsx
- packages/core/src/interface.ts
- packages/docs/content/docs/configuration-options.mdx
Hi, I added a new config `logo_link` which when set wraps the logo in the top left corner in an anchor/link.
The link can be set to another page or to a page in cms giving you a quick access to your fav page (it is like a home button which will transfer to your index page).
In the next major version, it would be good to group `logo_url` and `logo_link` in one object/setting, like `logo: { url: "...", link: "..." }`.
> feat: add a new setting logo_link

- packages/core/src/widgets/datetime/DateTimeControl.tsx
I am migrating a website from Decap/NetlifyCMS and I have an issue with existing dates not being parsed.
The dates are stored as `2024-02-25T18:30:00.000Z` (ISO format) and date-fns tries to parse it with the format `"yyyy-MM-dd'T'HH:mm:ssXXX"` (which does not raise an exception, but returns an Invalid Date): https://date-fns.org/v3.3.1/docs/parse
> If parsing failed, Invalid Date will be returned. Invalid Date is a Date, whose time value is NaN. Time value of Date: http://es5.github.io/#x15.9.1.1
I don't mind storing them with the static-cms default, however it would be nice if static-cms could try harder to parse the date (instead of showing an empty date, losing the data).
> feat: fallback to date-fns.parseISO when date cannot be parsed

- packages/docs/content/docs/add-to-your-site-cdn.mdx
The code block in https://www.staticcms.org/docs/add-to-your-site-cdn#app-file-structure was using the ^3.0.0 URL.
This PR updates it to ^4.0.0
> docs: CDN Hosting use ^4.0.0

- packages/core/src/actions/config.ts
- packages/core/src/actions/entries.ts
- packages/core/src/components/collections/CollectionControls.tsx
- packages/core/src/components/collections/CollectionView.tsx
- packages/core/src/components/collections/FilterControl.tsx
- packages/core/src/components/collections/GroupControl.tsx
- packages/core/src/components/collections/entries/EntriesCollection.tsx
- packages/core/src/interface.ts
- packages/core/src/reducers/entries.ts
- packages/core/src/reducers/selectors/entries.ts
- packages/core/test/data/collections.mock.ts
> fix: properly handle default group and filter

- packages/core/src/backends/github/API.ts
- packages/core/src/backends/github/__tests__/API.spec.ts
- packages/core/src/backends/github/implementation.tsx
- packages/core/src/interface.ts
When looking to support custom authentication with Github (by proxying to Github API through a custom authenticated API), the `token` auth-scheme in the Authorization header may not be appropriate. 
For example, when looking to use AWS Lambda function to proxy Github API requests and using AWS Cognito for authentication (Cognito is the user management service offered by AWS out of the box), authenticated requests to the Lambda function must use `Bearer` scheme.
Note: Github API does seem to accept either `Bearer` or `token`, and even appears to prefer and sometimes mandate `Bearer` according to their API docs:
https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28#about-authentication
However - changing this would be a potentially breaking …
> feat: Support custom auth schemes for Github API

- packages/core/src/backend.ts
- packages/core/src/lib/formatters.ts
- packages/core/src/lib/widgets/stringTemplate.ts
- packages/docs/content/docs/configuration-options.mdx
This PR solves https://github.com/StaticJsCMS/static-cms/issues/1104
> feat: allow custom fields inside git commit message

- packages/core/src/components/entry-editor/EditorToolbar.css
- packages/core/src/components/entry-editor/EditorToolbar.tsx
> fix: discard on mobile

- packages/core/dev-test/config.yml
- packages/core/src/actions/__tests__/config.spec.ts
- packages/core/src/actions/config.ts
- packages/core/src/components/entry-editor/editor-control-pane/EditorControl.tsx
- packages/core/src/components/entry-editor/editor-control-pane/EditorControlPane.tsx
- packages/core/src/constants/configSchema.tsx
- packages/core/src/interface.ts
- packages/core/src/lib/i18n.ts
- packages/core/src/reducers/__tests__/entryDraft.spec.ts
- packages/docs/content/docs/i18n-support.mdx
> feat: make non default locales optional
