- .eslintrc.js
- package.json
- src/backends/gitlab/AuthenticationPage.tsx
- src/components/Editor/Editor.tsx
- src/components/Editor/EditorControlPane/EditorControl.tsx
- src/components/UI/ListItemTopBar.tsx
- src/constants/files.ts
- src/editor-components/editorPlugin.ts
- src/interface.ts
- src/lib/util/fetch.util.ts
- src/lib/util/validation.util.ts
- src/store/slices/snackbars.ts
- src/widgets/markdown/MarkdownControl.tsx
- src/widgets/select/SelectControl.tsx
- src/widgets/text/TextControl.tsx
- website/src/components/github-button.js
- yarn.lock
> Feature/toast UI editor

- website/content/docs/local-backend.mdx
Update documentation to properly reflect the code
> Update local-backend.mdx default port URL string

- CONTRIBUTING.md
- core/tsconfig.base.json
- core/webpack.config.js
Added the `cd core` to the contributing docs
Enable generation of source maps in builds
> feat: improve contribution docs and add source maps to build

- packages/core/.eslintrc.js
- packages/core/src/backends/proxy/implementation.ts
> fix: implement allEntriesByFolder for proxy backend

- .github/workflows/build.yml
- packages/core/dev-test/config.yml
- packages/core/src/widgets/datetime/DateTimeControl.tsx
> fix: handle date/time only when display format not provided

- packages/docs/content/docs/beta-features.mdx
This PR fixes the indentation of yaml for one of the i18n yaml configurations
> docs: fixed i18n yaml indentation

- packages/docs/src/components/layout/search/SearchModal.tsx
- packages/docs/src/components/layout/search/SearchResult.tsx
> fix: docs search box closing too fast

- packages/docs/src/components/layout/search/SearchModal.tsx
> fix: docs search resets on result click

- packages/core/src/components/UI/ListItemTopBar.tsx
> fix: cut off title with ellipsis if too long

- packages/core/webpack.config.js
> fix: automatic public path

- packages/core/src/lib/i18n.ts
- packages/core/src/reducers/__tests__/entryDraft.spec.ts
- packages/core/src/reducers/entryDraft.ts
- yarn.lock
> fix: i18n duplicate fields

- packages/core/src/actions/entries.ts
- packages/core/src/components/App/App.tsx
- packages/core/src/components/Editor/Editor.tsx
- packages/core/src/components/Editor/EditorInterface.tsx
Fix the following actions:
- Redirecting to newly saved entry
- Duplicating new and existing entries
- Publish and create
Resolves #592
> fix: duplicate create new

- packages/core/src/components/entry-editor/EditorToolbar.tsx
- packages/core/src/components/navbar/QuickCreate.tsx
- packages/core/src/locales/de/index.ts
This PR makes some strings translatable and updates some German translations
> fix: translation updates

- packages/core/dev-test/config.yml
- packages/core/src/components/common/field/ErrorMessage.tsx
- packages/core/src/locales/en/index.ts
- packages/core/src/widgets/colorstring/ColorControl.tsx
- packages/core/src/widgets/colorstring/__tests__/ColorControl.spec.ts
- packages/core/src/widgets/colorstring/__tests__/validator.spec.ts
- packages/core/src/widgets/colorstring/index.ts
- packages/core/src/widgets/colorstring/validator.ts
- packages/core/src/widgets/select/__tests__/SelectControl.spec.ts
- packages/core/test/data/fields.mock.ts
- packages/demo/public/config.yml
> fix: improve color widget, add tests

- packages/core/src/widgets/markdown/plate/components/buttons/FontTypeSelect.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/headings/Heading1.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/headings/Heading2.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/headings/Heading3.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/headings/Heading4.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/headings/Heading5.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/headings/Heading6.tsx
- packages/core/src/widgets/markdown/plate/components/toolbar/Toolbar.tsx
> feat: make markdown toolbar sticky

- packages/core/dev-test/index.html
- packages/core/src/components/media-library/common/MediaLibrary.tsx
- packages/core/src/reducers/mediaLibrary.ts
> fix: media config top level

- packages/core/src/actions/config.ts
- packages/core/src/actions/mediaLibrary.ts
- packages/core/src/actions/waitUntil.ts
- packages/core/src/backend.ts
- packages/core/src/backends/bitbucket/API.ts
- packages/core/src/backends/bitbucket/implementation.ts
- packages/core/src/backends/git-gateway/AuthenticationPage.tsx
- packages/core/src/backends/git-gateway/implementation.tsx
- packages/core/src/backends/gitea/API.ts
- packages/core/src/backends/gitea/implementation.tsx
- packages/core/src/backends/github/API.ts
- packages/core/src/backends/github/implementation.tsx
- packages/core/src/backends/gitlab/implementation.ts
- packages/core/src/bootstrap.tsx
- packages/core/src/components/App.tsx
- packages/core/src/components/ErrorBoundary.tsx
- packages/core/src/formats/frontmatter.ts
- packages/core/src/interface.ts
- packages/core/src/lib/formatters.ts
- packages/core/src/lib/i18n.ts
- packages/core/src/lib/registry.ts
- packages/core/src/lib/util/API.ts
- packages/core/src/lib/util/asyncLock.ts
- packages/core/src/lib/util/implementation.ts
- packages/core/src/lib/util/localForage.ts
- packages/core/src/reducers/selectors/entries.ts
- packages/core/src/widgets/list/components/ListItem.tsx
- packages/core/src/widgets/markdown/plate/serialization/serializeMarkdown.ts
- packages/core/src/widgets/markdown/plate/serialization/slate/deserializeMarkdown.ts
- packages/docs/content/docs/beta-features.mdx
> feat: events

- packages/core/src/__mocks__/@udecode/plate.ts
- packages/core/src/components/common/field/Field.tsx
- packages/core/src/components/common/image/Image.tsx
- packages/core/src/components/media-library/common/CurrentMediaDetails.tsx
- packages/core/src/components/media-library/common/InlineEditTextField.tsx
- packages/core/src/components/media-library/common/MediaLibrary.tsx
- packages/core/src/widgets/markdown/plate/PlateEditor.tsx
- packages/core/src/widgets/markdown/plate/components/balloon-toolbar/BalloonToolbar.tsx
- packages/core/src/widgets/markdown/plate/components/balloon-toolbar/__tests__/BalloonToolbar.spec.tsx
- packages/core/src/widgets/markdown/plate/components/buttons/AddButtons.tsx
- packages/core/src/widgets/markdown/plate/components/buttons/common/ImageToolbarButton.tsx
- packages/core/src/widgets/markdown/plate/components/buttons/common/LinkToolbarButton.tsx
- packages/core/src/widgets/markdown/plate/components/common/MediaPopover.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/table/TableCellElement/TableHeaderCellElement.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/table/TableElement/TableElement.tsx
- packages/docs/content/docs/widget-markdown.mdx
> fix: media library url entry

- packages/core/dev-test/backends/gitlab/config.yml
- packages/core/src/components/login/Login.tsx
- packages/core/src/components/navbar/Navbar.tsx
> fix: styles for custom logo and use custom logo in top nav bar

- packages/core/src/components/collections/FilterControl.tsx
> fix: filter checkbox not clickable

- packages/core/dev-test/config.yml
- packages/core/src/interface.ts
- packages/core/src/widgets/list/DelimitedListControl.tsx
- packages/core/src/widgets/list/ListControl.tsx
- packages/core/src/widgets/list/ListPreview.tsx
- packages/core/src/widgets/list/__tests__/ListControl.spec.tsx
- packages/core/src/widgets/list/components/ListItem.tsx
- packages/core/src/widgets/string/__tests__/StringControl.spec.ts
- packages/core/src/widgets/text/TextControl.tsx
- packages/core/src/widgets/text/__tests__/TextControl.spec.ts
- packages/demo/public/config.yml
- packages/docs/content/docs/widget-list.mdx
> feat: delimiter separated lists

- packages/core/src/backend.ts
- packages/core/src/lib/util/media.util.ts
- packages/core/src/reducers/mediaLibrary.ts
- packages/core/src/widgets/markdown/plate/PlateEditor.tsx
> fix: draft folder support

- packages/core/src/widgets/markdown/plate/serialization/slate/__tests__/autoLinkUrls.spec.ts
- packages/core/src/widgets/markdown/plate/serialization/slate/autoLinkUrls.ts
- packages/core/src/widgets/markdown/plate/serialization/slate/deserializeMarkdown.ts
- packages/core/src/widgets/relation/RelationControl.tsx
> fix: do not auto link url from text if already inside a link

- packages/core/src/components/common/button/Button.tsx
- packages/core/src/widgets/markdown/plate/components/buttons/InsertLinkToolbarButton.tsx
- packages/core/src/widgets/markdown/plate/components/common/MediaPopover.tsx
> fix: insert link for selected text behavior

- packages/core/src/components/entry-editor/EditorInterface.tsx
> fix: i18n reversion

- packages/core/dev-test/config.yml
- packages/core/src/components/common/text-field/TextArea.tsx
- packages/core/src/interface.ts
- packages/core/src/locales/en/index.ts
- packages/core/src/widgets/markdown/plate/PlateEditor.tsx
- packages/core/src/widgets/markdown/plate/editableProps.ts
- packages/core/src/widgets/markdown/plate/hooks/useMarkdownToSlate.ts
- packages/core/src/widgets/markdown/schema.ts
- packages/core/src/widgets/markdown/withMarkdownControl.tsx
> feat: add raw markdown editor

- packages/core/src/backend.ts
- packages/core/src/backends/git-gateway/implementation.tsx
- packages/core/src/backends/github/implementation.tsx
- packages/core/src/interface.ts
Related to decap PR: https://github.com/decaporg/decap-cms/pull/6898
> feat: filter entry list from github before reading files

- packages/core/src/actions/search.ts
- packages/core/src/constants.ts
- packages/core/src/interface.ts
- packages/core/src/reducers/search.ts
Related to Decap PR: https://github.com/decaporg/decap-cms/pull/6902
> feat: cache search results

- packages/core/src/widgets/markdown/plate/components/nodes/code-block/CodeBlockElement.tsx
- packages/core/src/widgets/markdown/plate/components/nodes/code-block/CodeBlockFrame.tsx
- packages/core/src/widgets/markdown/plate/plugins/code-block/createCodeBlockPlugin.ts
> fix: delete code block on backspace when code block is empty

- packages/core/src/components/collections/entries/EntryCard.tsx
- packages/core/src/components/collections/entries/EntryRow.tsx
> fix: has local backup icon appearing when local backups are disabled

- packages/core/package.json
- packages/core/src/components/MainView.tsx
- packages/core/src/components/entry-editor/EditorInterface.css
- packages/core/src/components/entry-editor/EditorInterface.tsx
- packages/core/src/components/entry-editor/editor-preview-pane/EditorPreviewPane.css
- packages/core/src/components/entry-editor/editor-preview-pane/EditorPreviewPane.tsx
- yarn.lock
> feat: resizable-editor

- packages/core/src/lib/util/string.util.ts
- packages/core/src/widgets/markdown/plate/components/nodes/blockquote/BlockquoteElement.css
- packages/core/src/widgets/markdown/plate/plugins/soft-break/softBreakPlugin.ts
- packages/core/src/widgets/markdown/plate/serialization/serializeMarkdown.ts
- packages/core/src/widgets/markdown/plate/serialization/slate/deserializeMarkdown.ts
- packages/core/src/widgets/markdown/plate/tests-util/serializationTests.util.tsx
> fix: blockquote newline

- packages/core/src/interface.ts
> fix: change show_raw interface definition to boolean

- packages/core/src/reducers/entryDraft.ts
Fixes #944 
Fixes #943 
Related to #946
> fix: properly detect changes

- packages/docs/content/docs/configuration-options.mdx
- packages/docs/content/docs/test-backend.mdx
Thanks for this nifty fork, really love the UI and capabilities :)
> docs: fix url to demo instance

- packages/core/dev-test/config.yml
- packages/core/src/lib/formatters.ts
- packages/core/src/lib/util/__tests__/media.util.spec.ts
- packages/core/src/lib/util/media.util.ts
> fix: only add public folder if path matches media folder

- packages/core/src/backend.ts
- packages/core/src/components/collections/entries/Entries.tsx
- packages/core/src/components/collections/entries/EntryRow.tsx
- packages/core/src/widgets/relation/RelationControl.tsx
- packages/core/src/widgets/relation/RelationSummary.tsx
- packages/core/src/widgets/relation/index.ts
- packages/core/src/widgets/relation/types.ts
- packages/core/src/widgets/relation/util.ts
> feat: add rich summary for relation fields when used as summary field

- packages/core/src/backend.ts
- packages/core/src/constants/mediaLibrary.ts
- packages/core/src/lib/formatters.ts
- packages/core/src/lib/util/__tests__/media.util.spec.ts
- packages/core/src/lib/util/entry.util.ts
- packages/core/src/lib/util/media.util.ts
> fix: media public path conversion

- packages/core/src/actions/__tests__/config.spec.ts
- packages/core/src/actions/config.ts
> fix: global media_library not propagating to fields

- packages/core/src/components/theme/hooks/useThemes.ts
> fix: include_built_in_themes not working

- packages/docs/src/components/docs/table_of_contents/DocsTableOfContents.tsx
- packages/docs/src/components/layout/Page.tsx
- packages/docs/src/pages/community.tsx
- packages/docs/src/pages/releases.tsx
- tailwind.base.config.js
Fixes #1011 
See https://web.dev/blog/viewport-units
> fix: use dynamic view height for mobile support

- packages/core/src/components/navbar/Navbar.css
> fix: site url icon size

- packages/core/src/components/common/field/Hint.css
- packages/core/src/widgets/object/ObjectControl.css
- packages/core/src/widgets/relation/RelationControl.css
<details><summary>Before:</summary>
</details>
<details><summary>After:</summary>
> fix: Small style fixes

- packages/core/src/locales/cs/index.ts
Hello, I just added a few translations to cs lang file.
> fix: add cs translations

- packages/docs/content/docs/updating-your-cms.mdx
There's no `5.0.0` yet but I believe this is what the docs meant.
> docs: fixing version listed
